openapi: 3.0.3
info:
  version: 1.0.0
  title: Account Service
  description: API for managing user accounts, authentication, and authorization.
servers:
  - url: 'http:/localhost:8080/api'
paths:
  /user/all:
    get:
      tags:
        - Account
      summary: Getting all users
      operationId: getAllUsers
      responses:
        "201":
          description: Successful retrieval of all users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'

        "400":

          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /user/{id}:
    get:
      tags:
        - Account
      summary: Getting single user by id
      operationId: getUserById
      responses:
        "201":
          description: Successful retrieval of user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
          in: query
          name: User Id
  /user/{id}/rights:
    get:
      tags:
        - Account
      summary: Getting single user's rights by id
      operationId: getUserRightsById
      responses:
        "201":
          description: Successful retrieval of user rights.
          content:
            application/json:
              schema:
                type: string
                enum:
                  - ADMIN
                  - USER

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
          in: query
          name: User Id
  /user/{email}:
    get:
      tags:
        - Account
      summary: Getting single user by email
      operationId: getUserByEmail
      responses:
        "201":
          description: Successful retrieval of user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            type: string
          in: query
          name: User email
  /user/{id}/update:
    get:
      tags:
        - Account
      summary: Update user
      operationId: updateUser
      responses:
        "201":
          description: Successful update of user.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
      parameters:
        - schema:
            $ref: '#/components/schemas/UserDTO'
          in: query
          name: Updated user
components:
  schemas:
    ErrorDto:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    UserDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
        accountType:
          type: string
          enum:
            - ADMIN
            - USER